### ISSUE TITLE
everything about UI

### ISSUE THREAD

**Issue by naveenkumardot25** [vamshi9666/Musify-#3]
Hello

**Comment by naveenkumardot25** [comment]
Ok got it

**Comment by vamshi9666** [comment]
ok . as  i said before about manifest . content scripts deals anythng in webwiew

**Comment by naveenkumardot25** [comment]
ok

**Comment by vamshi9666** [comment]
but there is also a thing called "background"

**Comment by vamshi9666** [comment]
background deals about entire browser

**Comment by vamshi9666** [comment]
https://www.youtube.com/watch?v=ew9ut7ixIlI&t=589s 
check this vedio

**Comment by vamshi9666** [comment]
so we can change browser color and animations

**Comment by naveenkumardot25** [comment]
https://developer.mozilla.org/en-US/Add-ons/Themes/Theme_concepts 
can we do animations or graphics  in this place

**Comment by vamshi9666** [comment]
can we change colors of browser;s menu panel with that ?

**Comment by vamshi9666** [comment]
no we cant change them . we can just set them statically

**Comment by vamshi9666** [comment]
check new issue . i started

**Comment by naveenkumardot25** [comment]
ok

**Comment by vamshi9666** [comment]
@Stone2517  what is best way to show user playlist

**Comment by vamshi9666** [comment]
i mean like popup or sidebar or anything else?
